-- MySQL Script generated by MySQL Workbench
-- Thu May  7 22:55:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`publisher` (
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `tel_no` VARCHAR(20) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Book` (
  `ISBN` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `pyear` DATE NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `publisher_name` VARCHAR(100) NOT NULL,
  `stock_min` INT NOT NULL DEFAULT 0,
  `stock` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `fk_Book_publisher1`
    FOREIGN KEY (`publisher_name`)
    REFERENCES `bookstore`.`publisher` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `title_UNIQUE` ON `bookstore`.`Book` (`title` ASC) VISIBLE;

CREATE INDEX `fk_Book_publisher1_idx` ON `bookstore`.`Book` (`publisher_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bookstore`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`book_authors` (
  `Author_name` VARCHAR(100) NOT NULL,
  `Book_ISBN` INT NOT NULL,
  PRIMARY KEY (`Author_name`, `Book_ISBN`),
  CONSTRAINT `fk_book_authors_Book`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `bookstore`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_book_authors_Book_idx` ON `bookstore`.`book_authors` (`Book_ISBN` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bookstore`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`orders` (
  `quantity` INT NOT NULL,
  `Book_ISBN` INT NOT NULL,
  PRIMARY KEY (`Book_ISBN`),
  CONSTRAINT `fk_orders_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `bookstore`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`users` (
  `userName` VARCHAR(100) NOT NULL,
  `fname` VARCHAR(100) NOT NULL,
  `Lname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `shipAddress` VARCHAR(100) NULL,
  `phoneNum` VARCHAR(20) NOT NULL,
  `role` TINYINT NOT NULL DEFAULT 0 COMMENT 'role:\n0=> customer\n1=> manager',
  PRIMARY KEY (`userName`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `userName_UNIQUE` ON `bookstore`.`users` (`userName` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `bookstore`.`users` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `phoneNum_UNIQUE` ON `bookstore`.`users` (`phoneNum` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bookstore`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`sales` (
  `date` DATE NOT NULL,
  `no_of_copies` INT NULL DEFAULT 1,
  `userName` VARCHAR(100) NOT NULL,
  `Book_ISBN` INT NOT NULL,
  PRIMARY KEY (`userName`, `Book_ISBN`),
  CONSTRAINT `fk_sales_users1`
    FOREIGN KEY (`userName`)
    REFERENCES `bookstore`.`users` (`userName`)
    ON DELETE cascade`sales`
    ON UPDATE cascade,
  CONSTRAINT `fk_sales_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `bookstore`.`Book` (`ISBN`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;

CREATE INDEX `fk_sales_Book_idx` ON `bookstore`.`sales` (`Book_ISBN` ASC) INVISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
