-- MySQL Script generated by MySQL Workbench
-- Wed May  6 17:05:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`publisher` (
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `tel_no` VARCHAR(20) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`Book` (
  `ISBN` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `pyear` DATE NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `publisher_name` VARCHAR(100) NOT NULL,
  `stock_min` INT NOT NULL DEFAULT 0,
  `stock` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `fk_Book_publisher1`
    FOREIGN KEY (`publisher_name`)
    REFERENCES `bookstore`.`publisher` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `title_UNIQUE` ON `bookstore`.`Book` (`title` ASC) VISIBLE;

CREATE INDEX `fk_Book_publisher1_idx` ON `bookstore`.`Book` (`publisher_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bookstore`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`book_authors` (
  `Author_name` VARCHAR(100) NOT NULL,
  `Book_ISBN` INT NOT NULL,
  PRIMARY KEY (`Author_name`, `Book_ISBN`),
  CONSTRAINT `fk_book_authors_Book`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `bookstore`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_book_authors_Book_idx` ON `bookstore`.`book_authors` (`Book_ISBN` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bookstore`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`orders` (
  `quantity` INT NOT NULL,
  `Book_ISBN` INT NOT NULL,
  PRIMARY KEY (`Book_ISBN`),
  CONSTRAINT `fk_orders_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `bookstore`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
